const PORNOGRAPHIC = 'PORNOGRAPHIC'
const VIOLENT = 'VIOLENT'
const HATEFUL = 'HATEFUL'
const HARASSMENT = 'HARASSMENT'
const HARMFUL = 'HARMFUL'
const CHILD_ABUSE = 'CHILD_ABUSE'
const TERRORISTIC = 'TERRORISTIC'
const SPAM = 'SPAM'
const INFRIGEMENT = 'INFRIGEMENT'
const COMPLIANCE_ISSUE = 'COMPLIANCE_ISSUE'
const OTHER = 'OTHER'

const ViolationTypes = [
  PORNOGRAPHIC,
  VIOLENT,
  HATEFUL,
  HARASSMENT,
  HARMFUL,
  CHILD_ABUSE,
  TERRORISTIC,
  SPAM,
  INFRIGEMENT,
  COMPLIANCE_ISSUE,
  OTHER,
]

export { OTHER }
export default ViolationTypes
